// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TikTokTools.Data;

#nullable disable

namespace TikTokTools.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260218212148_TetMigration3")]
    partial class TetMigration3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("TikTokTools.Models.ApplicationConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ElevenLabsApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputFolderPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TempFolderPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TikTokApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppConfig");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ElevenLabsApiKey = "",
                            OutputFolderPath = "C:\\TikTokTools\\Output",
                            TempFolderPath = "C:\\TikTokTools\\Temp",
                            TikTokApiKey = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
